name: lg_flutter_stater_kit
description: "A production-ready Flutter Starter Kit for Liquid Galaxy Controllers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ› ï¸ State Management
  flutter_riverpod: ^2.5.1
  
  
  # ðŸ“¡ Liquid Galaxy Connection
  dartssh2: ^2.10.0
  
  # ðŸ” Security & Storage
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.3
  
  
  # ðŸ—ºï¸ Maps 
  google_maps_flutter: ^2.7.0
  
  # ðŸŒ Networking
  dio: ^5.5.0+1

  # ðŸ“‚ Utilities
  permission_handler: ^12.0.1
  
  # ðŸŽ¨ Icons
  cupertino_icons: ^1.0.6

  logger: ^2.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/image/
    - assets/kml/
